# Generated by Django 5.0.6 on 2024-06-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoPedido',
            fields=[
                ('cod_avaliacao_pedido', models.IntegerField(db_column='COD_AVALIACAO_PEDIDO', primary_key=True, serialize=False)),
                ('num_nota_avaliacao', models.IntegerField(blank=True, db_column='NUM_NOTA_AVALIACAO', null=True)),
                ('txt_avaliacao', models.CharField(blank=True, db_column='TXT_AVALIACAO', max_length=100, null=True)),
            ],
            options={
                'db_table': 'AVALIACAO_PEDIDO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('cod_bairro', models.IntegerField(db_column='COD_BAIRRO', primary_key=True, serialize=False)),
                ('dcr_bairro', models.CharField(blank=True, db_column='DCR_BAIRRO', max_length=45, null=True)),
            ],
            options={
                'db_table': 'BAIRRO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('cod_cardapio', models.IntegerField(db_column='COD_CARDAPIO', primary_key=True, serialize=False)),
                ('dcr_cardapio', models.CharField(blank=True, db_column='DCR_CARDAPIO', max_length=45, null=True)),
                ('dcr_titulo_apres', models.CharField(blank=True, db_column='DCR_TITULO_APRES', max_length=45, null=True)),
            ],
            options={
                'db_table': 'CARDAPIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cod_categoria', models.IntegerField(db_column='COD_CATEGORIA', primary_key=True, serialize=False)),
                ('dcr_categoria', models.CharField(blank=True, db_column='DCR_CATEGORIA', max_length=45, null=True)),
                ('img_categoria', models.TextField(blank=True, db_column='IMG_CATEGORIA', null=True)),
            ],
            options={
                'db_table': 'CATEGORIA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('cod_cidade', models.IntegerField(db_column='COD_CIDADE', primary_key=True, serialize=False)),
                ('dcr_cidade', models.CharField(blank=True, db_column='DCR_CIDADE', max_length=45, null=True)),
            ],
            options={
                'db_table': 'CIDADE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cliente', models.IntegerField(db_column='COD_CLIENTE', primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(blank=True, db_column='NOME_CLIENTE', max_length=45, null=True)),
                ('dcr_endereco', models.CharField(blank=True, db_column='DCR_ENDERECO', max_length=45, null=True)),
                ('dcr_complemento', models.CharField(blank=True, db_column='DCR_COMPLEMENTO', max_length=45, null=True)),
                ('num_cep', models.CharField(blank=True, db_column='NUM_CEP', max_length=10, null=True)),
            ],
            options={
                'db_table': 'CLIENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisponExcecao',
            fields=[
                ('cod_dispon_excecao', models.IntegerField(db_column='COD_DISPON_EXCECAO', primary_key=True, serialize=False)),
                ('data_excecao', models.DateTimeField(blank=True, db_column='DATA_EXCECAO', null=True)),
                ('tip_excecao', models.CharField(blank=True, db_column='TIP_EXCECAO', max_length=1, null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, db_column='HORA_INICIO', null=True)),
                ('hora_fim', models.DateTimeField(blank=True, db_column='HORA_FIM', null=True)),
            ],
            options={
                'db_table': 'DISPON_EXCECAO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('cod_disponibilidade', models.IntegerField(db_column='COD_DISPONIBILIDADE', primary_key=True, serialize=False)),
                ('num_dia_semana', models.IntegerField(blank=True, db_column='NUM_DIA_SEMANA', null=True)),
                ('hora_fim', models.DateTimeField(blank=True, db_column='HORA_FIM', null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, db_column='HORA_INICIO', null=True)),
            ],
            options={
                'db_table': 'DISPONIBILIDADE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('cod_empreedimento', models.IntegerField(db_column='COD_EMPREEDIMENTO', primary_key=True, serialize=False)),
                ('dcr_empreendimento', models.CharField(blank=True, db_column='DCR_EMPREENDIMENTO', max_length=45, null=True)),
                ('dcr_nome_fantasia', models.CharField(blank=True, db_column='DCR_NOME_FANTASIA', max_length=45, null=True)),
                ('dcr_endereco', models.CharField(blank=True, db_column='DCR_ENDERECO', max_length=45, null=True)),
                ('dcr_complemento', models.CharField(blank=True, db_column='DCR_COMPLEMENTO', max_length=45, null=True)),
                ('num_cep', models.CharField(blank=True, db_column='NUM_CEP', max_length=10, null=True)),
                ('img_empreendimento', models.TextField(blank=True, db_column='IMG_EMPREENDIMENTO', null=True)),
            ],
            options={
                'db_table': 'EMPREENDIMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmprendFuncionario',
            fields=[
                ('cod_empreend_funcionario', models.IntegerField(db_column='COD_EMPREEND_FUNCIONARIO', primary_key=True, serialize=False)),
                ('tip_funcionario', models.CharField(blank=True, db_column='TIP_FUNCIONARIO', max_length=1, null=True)),
                ('img_empreend_funcionario', models.TextField(blank=True, db_column='IMG_EMPREEND_FUNCIONARIO', null=True)),
            ],
            options={
                'db_table': 'EMPREND_FUNCIONARIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('cod_entrega', models.IntegerField(db_column='COD_ENTREGA', primary_key=True, serialize=False)),
                ('data_saida', models.DateTimeField(blank=True, db_column='DATA_SAIDA', null=True)),
                ('data_entrega', models.DateTimeField(blank=True, db_column='DATA_ENTREGA', null=True)),
                ('vlr_entrega', models.DecimalField(blank=True, db_column='VLR_ENTREGA', decimal_places=2, max_digits=9, null=True)),
                ('dcr_endereco', models.CharField(blank=True, db_column='DCR_ENDERECO', max_length=45, null=True)),
                ('dcr_complem', models.CharField(blank=True, db_column='DCR_COMPLEM', max_length=45, null=True)),
                ('num_cep', models.CharField(blank=True, db_column='NUM_CEP', max_length=10, null=True)),
                ('txt_referencia', models.CharField(blank=True, db_column='TXT_REFERENCIA', max_length=45, null=True)),
                ('flag_encomenda', models.CharField(blank=True, db_column='FLAG_ENCOMENDA', max_length=1, null=True)),
                ('flag_entregador', models.CharField(blank=True, db_column='FLAG_ENTREGADOR', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ENTREGA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('cod_evento', models.IntegerField(db_column='COD_EVENTO', primary_key=True, serialize=False)),
                ('dcr_evento', models.CharField(blank=True, db_column='DCR_EVENTO', max_length=45, null=True)),
                ('num_ordem_evento', models.IntegerField(blank=True, db_column='NUM_ORDEM_EVENTO', null=True)),
            ],
            options={
                'db_table': 'EVENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormaPagto',
            fields=[
                ('cod_forma_pagto', models.IntegerField(db_column='COD_FORMA_PAGTO', primary_key=True, serialize=False)),
                ('dcr_forma_pagto', models.CharField(blank=True, db_column='DCR_FORMA_PAGTO', max_length=45, null=True)),
            ],
            options={
                'db_table': 'FORMA_PAGTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('cod_funcionario', models.IntegerField(db_column='COD_FUNCIONARIO', primary_key=True, serialize=False)),
                ('nome_funcionario', models.CharField(blank=True, db_column='NOME_FUNCIONARIO', max_length=45, null=True)),
                ('num_telefone', models.CharField(blank=True, db_column='NUM_TELEFONE', max_length=15, null=True)),
                ('dcr_email', models.CharField(blank=True, db_column='DCR_EMAIL', max_length=45, null=True)),
            ],
            options={
                'db_table': 'FUNCIONARIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('cod_item_pedido', models.IntegerField(db_column='COD_ITEM_PEDIDO', primary_key=True, serialize=False)),
                ('vlr_produto', models.DecimalField(blank=True, db_column='VLR_PRODUTO', decimal_places=2, max_digits=9, null=True)),
                ('qtd_produto', models.DecimalField(blank=True, db_column='QTD_PRODUTO', decimal_places=2, max_digits=9, null=True)),
                ('vlr_total', models.DecimalField(blank=True, db_column='VLR_TOTAL', decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'ITEM_PEDIDO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('cod_localidade', models.IntegerField(db_column='COD_LOCALIDADE', primary_key=True, serialize=False)),
                ('dcr_localidade', models.CharField(blank=True, db_column='DCR_LOCALIDADE', max_length=45, null=True)),
            ],
            options={
                'db_table': 'LOCALIDADE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cod_pedido', models.IntegerField(db_column='COD_PEDIDO', primary_key=True, serialize=False)),
                ('tip_pedido', models.CharField(blank=True, db_column='TIP_PEDIDO', max_length=1, null=True)),
                ('data_pedido', models.DateTimeField(blank=True, db_column='DATA_PEDIDO', null=True)),
                ('vlr_pedido', models.DecimalField(blank=True, db_column='VLR_PEDIDO', decimal_places=2, max_digits=9, null=True)),
                ('dcr_dados_pagto', models.CharField(blank=True, db_column='DCR_DADOS_PAGTO', max_length=200, null=True)),
            ],
            options={
                'db_table': 'PEDIDO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('cod_produto', models.IntegerField(db_column='COD_PRODUTO', primary_key=True, serialize=False)),
                ('dcr_produto', models.CharField(blank=True, db_column='DCR_PRODUTO', max_length=45, null=True)),
                ('img_produto', models.TextField(blank=True, db_column='IMG_PRODUTO', null=True)),
                ('vlr_produto', models.DecimalField(blank=True, db_column='VLR_PRODUTO', decimal_places=2, max_digits=9, null=True)),
                ('flag_disponivel', models.CharField(blank=True, db_column='FLAG_DISPONIVEL', max_length=1, null=True)),
            ],
            options={
                'db_table': 'PRODUTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RastreamentoPedido',
            fields=[
                ('cod_rastreamento_pedido', models.IntegerField(db_column='COD_RASTREAMENTO_PEDIDO', primary_key=True, serialize=False)),
                ('data_hora_evento', models.DateTimeField(blank=True, db_column='DATA_HORA_EVENTO', null=True)),
            ],
            options={
                'db_table': 'RASTREAMENTO_PEDIDO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecaoCardapio',
            fields=[
                ('cod_secao_cardapio', models.IntegerField(db_column='COD_SECAO_CARDAPIO', primary_key=True, serialize=False)),
                ('dcr_secao_cardapio', models.CharField(blank=True, db_column='DCR_SECAO_CARDAPIO', max_length=45, null=True)),
                ('dcr_titulo_apres', models.CharField(blank=True, db_column='DCR_TITULO_APRES', max_length=45, null=True)),
                ('num_ordem', models.IntegerField(blank=True, db_column='NUM_ORDEM', null=True)),
            ],
            options={
                'db_table': 'SECAO_CARDAPIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecaoProduto',
            fields=[
                ('cod_secao_produto', models.CharField(db_column='COD_SECAO_PRODUTO', max_length=45, primary_key=True, serialize=False)),
                ('num_ordem', models.CharField(blank=True, db_column='NUM_ORDEM', max_length=45, null=True)),
            ],
            options={
                'db_table': 'SECAO_PRODUTO',
                'managed': False,
            },
        ),
    ]
